services:
  markitdown:
    build: .
    container_name: markitdown
    volumes:
      - ./:/app
      - ./input:/input
      - ./output:/output
      - hf-cache:/root/.cache/huggingface
    working_dir: /app
    tty: true

volumes:
  hf-cache:
