#!/bin/bash
#
# ats_workflow.sh — Single-entry orchestrator for the full multi-variant
# ATS workflow. Chains build_variant_bank → variant_rank → prepare_variant
# → smart_chunk → ats_optimize → ats_recommend.
#
# SPLIT-PROMPT ARCHITECTURE (changed from monolithic):
# Stage 0/1 now uses two separate files instead of one monolithic prompt:
#   prompts/variant_bank.txt  — static; built once by build_variant_bank.sh
#   prompts/jd_current.txt    — JD-only; generated by variant_rank.sh
#
# Both files must be uploaded to Claude.ai together. This eliminates
# regenerating 30-50KB of identical variant content on every JD run.
# The bank is rebuilt automatically when stale, or pass --rebuild-bank
# to force.
#
# MODEL SWAPPING: set via --model flag or OLLAMA_MODEL env var.
# Stage 0/1 still recommended for Claude.ai (multi-document reasoning);
# Stages 2-4 can run locally with adequate local models.
#
# Usage:
#   ./scripts/ats_workflow.sh "output/JD.md" "output/resume" [--model llama3.1:8b]
#   ./scripts/ats_workflow.sh "output/JD.md" "output/resume" --rebuild-bank
#
set -e

JD_PATH="$1"
VARIANT_DIR="${2:-output/resume}"
MODEL="$OLLAMA_MODEL"
MODEL_EXPLICITLY_SET=false
REBUILD_BANK=false
[ -n "$MODEL" ] && MODEL_EXPLICITLY_SET=true

shift 2 2>/dev/null || true
while [ $# -gt 0 ]; do
  case "$1" in
    --model)
      MODEL="$2"
      MODEL_EXPLICITLY_SET=true
      shift 2
      ;;
    --rebuild-bank)
      REBUILD_BANK=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [ -z "$JD_PATH" ]; then
  echo "❌ Usage: ./scripts/ats_workflow.sh <jd.md> [variant_dir] [--model <name>] [--rebuild-bank]"
  echo "   Example: ./scripts/ats_workflow.sh \"output/JD1.md\" \"output/resume\" --model deepseek-r1:14b"
  exit 1
fi

if [ "$MODEL_EXPLICITLY_SET" = false ]; then
  OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
  echo "🔍 No --model given — checking which models are available in Ollama..."
  TAGS_RESPONSE=$(curl -s --max-time 5 "$OLLAMA_URL/api/tags" 2>&1) || {
    echo "❌ Could not reach Ollama at $OLLAMA_URL to list models. Is it running?"
    echo "   Or pass --model explicitly: --model <name>"
    exit 1
  }

  AVAILABLE_MODELS=$(echo "$TAGS_RESPONSE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for i, m in enumerate(data.get('models', []), 1):
    ctx = m.get('details', {}).get('context_length', '?')
    print(f\"{i}. {m.get('name')} (context: {ctx})\")
")

  if [ -z "$AVAILABLE_MODELS" ]; then
    echo "❌ No models found in Ollama. Pull one first: ollama pull <model>"
    exit 1
  fi

  echo ""
  echo "Available models:"
  echo "$AVAILABLE_MODELS"
  echo ""
  read -p "Enter the exact model name to use (e.g. deepseek-r1:14b): " MODEL

  if [ -z "$MODEL" ]; then
    echo "❌ No model selected. Re-run with --model <name> or select one above."
    exit 1
  fi
fi

if [ ! -f "$JD_PATH" ]; then
  echo "❌ JD file not found: $JD_PATH"
  exit 1
fi

echo "════════════════════════════════════════════════════════════"
echo "  ATS Workflow — model: $MODEL"
echo "════════════════════════════════════════════════════════════"
echo ""

# ─────────────────────────────────────────────────────────────────────
# PRE-STAGE — Build or verify variant bank
# ─────────────────────────────────────────────────────────────────────
echo "▶ PRE-STAGE — Variant bank check"
if [ "$REBUILD_BANK" = true ]; then
  echo "   --rebuild-bank flag set — rebuilding prompts/variant_bank.txt"
  ./scripts/build_variant_bank.sh --rebuild "$VARIANT_DIR"
else
  ./scripts/build_variant_bank.sh "$VARIANT_DIR"
fi
echo ""

# ─────────────────────────────────────────────────────────────────────
# STAGE 0/1 — Generate JD file; user uploads both to Claude.ai
# ─────────────────────────────────────────────────────────────────────
echo "▶ STAGE 0/1 — Generate JD file for Claude.ai upload"
./scripts/variant_rank.sh "$JD_PATH" "$VARIANT_DIR"

echo ""
echo "⚠️  STAGE 0/1 RECOMMENDATION: upload BOTH files to Claude.ai"
echo "   (multi-document reasoning — local 8B models fail this task)."
echo "   Files:"
echo "     prompts/variant_bank.txt  (static — reuse across JDs)"
echo "     prompts/jd_current.txt    (this JD)"
echo "   Policy classification: manual_only"
echo ""
read -p "   Auto-run on Ollama ($MODEL) anyway? [y/N] " RUN_STAGE_0
if [[ "$RUN_STAGE_0" =~ ^[Yy]$ ]]; then
  # For Ollama, combine both files into a single temp prompt since Ollama
  # doesn't support multi-file upload natively.
  COMBINED_PROMPT=$(mktemp /tmp/combined_variant_rank_XXXXXX.txt)
  cat prompts/variant_bank.txt prompts/jd_current.txt > "$COMBINED_PROMPT"
  ./scripts/llm_execute.sh "$COMBINED_PROMPT" stage_0_1_variant_rank "$MODEL" --override --force
  rm -f "$COMBINED_PROMPT"
  echo ""
  echo "📄 Result: prompts/variant_rank_prompt_response.txt"
  echo "   Verify the named variant(s) appear in your resume bank"
  echo "   and that the reasoning makes sense before trusting it."
else
  echo "   Skipped. Upload both prompt files to Claude.ai,"
  echo "   then come back and enter the chosen variant below."
fi

echo ""
echo "────────────────────────────────────────────────────────────"
read -p "Enter the chosen variant filename (e.g. Nanditha_Murthy_Resume_eBay.md): " CHOSEN_VARIANT

if [ -z "$CHOSEN_VARIANT" ]; then
  echo "❌ No variant given. Exiting — re-run when you've decided."
  exit 1
fi

CHOSEN_VARIANT_PATH="$VARIANT_DIR/$CHOSEN_VARIANT"
if [ ! -f "$CHOSEN_VARIANT_PATH" ]; then
  echo "❌ Variant not found at $CHOSEN_VARIANT_PATH"
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────
# STAGE 1.5 — Isolate the chosen variant
# ─────────────────────────────────────────────────────────────────────
echo ""
echo "▶ STAGE 1.5 — Isolating chosen variant"
./scripts/prepare_variant.sh "$CHOSEN_VARIANT_PATH" "$JD_PATH"

echo ""
echo "▶ Re-chunking (single variant only)"
./scripts/smart_chunk.sh

JD_BASENAME=$(basename "${JD_PATH%.*}")
rm -f "chunks/${JD_BASENAME}_part_"*.md
echo "🧹 Removed JD's own chunks from chunks/ (prevents JD-matches-itself retrieval bug)"

VARIANT_NAME="${CHOSEN_VARIANT%.*}"

# ─────────────────────────────────────────────────────────────────────
# STAGE 2 — ATS score
# ─────────────────────────────────────────────────────────────────────
echo ""
echo "▶ STAGE 2 — ATS evaluation"
./scripts/ats_optimize.sh "$JD_PATH" "output/$CHOSEN_VARIANT"

echo ""
echo "✅ Single-resume task — policy classification: local_allowed (advisory"
echo "   trust — spot-check Critical Gaps section specifically)."
read -p "   Auto-run on Ollama ($MODEL)? [Y/n] " RUN_STAGE_2
if [[ ! "$RUN_STAGE_2" =~ ^[Nn]$ ]]; then
  ./scripts/llm_execute.sh prompts/ats_prompt.txt stage_2_ats_optimize "$MODEL"
  echo "📄 Result: prompts/ats_prompt_response.txt"
else
  echo "   Skipped. Upload prompts/ats_prompt.txt to Claude.ai manually."
fi

# ─────────────────────────────────────────────────────────────────────
# STAGE 3 — File-level recommendations
# ─────────────────────────────────────────────────────────────────────
echo ""
echo "▶ STAGE 3 — File-level edit recommendations"
./scripts/ats_recommend.sh "$JD_PATH" "$VARIANT_NAME"

echo ""
echo "⚠️  STAGE 3 RECOMMENDATION: this prompt embeds ALL chunks of the"
echo "   chosen resume — a multi-section reasoning task. Claude.ai is"
echo "   recommended. Policy classification: manual_only."
read -p "   Auto-run on Ollama ($MODEL) anyway? [y/N] " RUN_STAGE_3
if [[ "$RUN_STAGE_3" =~ ^[Yy]$ ]]; then
  ./scripts/llm_execute.sh prompts/ats_recommend_prompt.txt stage_3_ats_recommend "$MODEL" --override --force
  echo "📄 Result: prompts/ats_recommend_prompt_response.txt"
else
  echo "   Skipped. Upload prompts/ats_recommend_prompt.txt to Claude.ai."
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Workflow complete."
echo "════════════════════════════════════════════════════════════"
echo "  All prompts are in prompts/ — use them with Claude.ai any time."
echo ""
echo "  Split-prompt reminder for Stage 0/1:"
echo "    prompts/variant_bank.txt  (reuse for every JD — rebuild only"
echo "      when variants change: ./scripts/build_variant_bank.sh --rebuild)"
echo "    prompts/jd_current.txt    (unique per JD run)"
