#!/bin/bash
#
# build_variant_bank.sh — One-time (or on-change) generator for the static
# variant bank prompt file: prompts/variant_bank.txt
#
# WHY THIS EXISTS:
# variant_rank.sh previously baked the JD directly into the same prompt as
# all resume variants. Since variants never change between JD runs — only
# the JD changes — this caused the full variant content to be regenerated
# and re-embedded on every single JD evaluation. For a bank of 15-20
# variants (each 1,500-2,500 words), that's 30-50KB of identical content
# regenerated on every run.
#
# This script separates the invariant part (variant bank + evaluation
# instructions) from the variable part (the JD). Output:
#
#   prompts/variant_bank.txt  — static; reuse across all JD evaluations
#
# The JD is supplied separately at evaluation time via variant_rank.sh,
# which now only writes a small prompts/jd_current.txt file and instructs
# the user to upload BOTH files to Claude.ai together.
#
# WHEN TO RE-RUN:
#   - First time (no prompts/variant_bank.txt exists yet)
#   - When you add, remove, or edit any resume variant in output/resume/
#   - When you want to force a rebuild: pass --rebuild flag
#
# The script auto-detects staleness by comparing the bank file's mtime
# against the most recently modified variant. If any variant is newer than
# the bank, it warns and exits unless --rebuild is passed.
#
# Usage:
#   ./scripts/build_variant_bank.sh                    # build if missing/stale
#   ./scripts/build_variant_bank.sh --rebuild          # force rebuild
#   ./scripts/build_variant_bank.sh "output/resume"   # custom variant dir
#
set -e

VARIANT_DIR="${1:-output/resume}"
REBUILD=false

# Handle --rebuild flag anywhere in args
for arg in "$@"; do
  if [ "$arg" = "--rebuild" ]; then
    REBUILD=true
    VARIANT_DIR="${1:-output/resume}"
  fi
done
# If only arg is --rebuild, reset dir to default
if [ "$VARIANT_DIR" = "--rebuild" ]; then
  VARIANT_DIR="output/resume"
fi

if [ ! -d "$VARIANT_DIR" ]; then
  echo "❌ Variant directory not found: $VARIANT_DIR"
  echo "   Create output/resume/ and add your resume .md variants there first."
  exit 1
fi

VARIANT_FILES=$(ls "$VARIANT_DIR"/*.md 2>/dev/null || true)

if [ -z "$VARIANT_FILES" ]; then
  echo "❌ No .md files found in $VARIANT_DIR"
  echo "   Run ./run.sh first to convert PDFs, or add .md resumes manually."
  exit 1
fi

# Build array for counting (requires bash — shebang guarantees this)
VARIANT_FILE_LIST=()
for f in "$VARIANT_DIR"/*.md; do
  [ -f "$f" ] && VARIANT_FILE_LIST+=("$f")
done

mkdir -p prompts
BANK_FILE="prompts/variant_bank.txt"

# ── Staleness check ───────────────────────────────────────────────────────────
if [ "$REBUILD" = false ] && [ -f "$BANK_FILE" ]; then
  BANK_MTIME=$(stat -c %Y "$BANK_FILE" 2>/dev/null || stat -f %m "$BANK_FILE" 2>/dev/null)
  NEWEST_VARIANT_MTIME=0
  NEWEST_VARIANT_NAME=""
  for f in "${VARIANT_FILE_LIST[@]}"; do
    FMTIME=$(stat -c %Y "$f" 2>/dev/null || stat -f %m "$f" 2>/dev/null)
    if [ "$FMTIME" -gt "$NEWEST_VARIANT_MTIME" ]; then
      NEWEST_VARIANT_MTIME=$FMTIME
      NEWEST_VARIANT_NAME=$(basename "$f")
    fi
  done

  if [ "$NEWEST_VARIANT_MTIME" -le "$BANK_MTIME" ]; then
    echo "✅ prompts/variant_bank.txt is up to date (${#VARIANT_FILE_LIST[@]} variants)."
    echo "   Pass --rebuild to force regeneration."
    echo ""
    echo "👉 Next: ./scripts/variant_rank.sh <jd_file>"
    exit 0
  else
    echo "⚠️  Variant '$NEWEST_VARIANT_NAME' is newer than prompts/variant_bank.txt."
    echo "   Rebuilding bank to include latest changes..."
    echo ""
  fi
fi

echo "📦 Found ${#VARIANT_FILE_LIST[@]} resume variant(s) in $VARIANT_DIR"
echo "🏗️  Building static variant bank prompt..."

VARIANT_COUNT=${#VARIANT_FILE_LIST[@]}
VARIANT_INVENTORY=""
for f in "${VARIANT_FILE_LIST[@]}"; do
  filename=$(basename "$f")
  content=$(cat "$f")
  VARIANT_INVENTORY="${VARIANT_INVENTORY}

### VARIANT: ${filename}
${content}

---"
done

cat > "$BANK_FILE" << EOF
# IMPORTANT — HOW TO USE THIS FILE
#
# This file contains the evaluation instructions and ALL resume variants.
# It is INCOMPLETE on its own — it requires the Job Description to be
# supplied as a SEPARATE ATTACHMENT.
#
# Upload BOTH files to Claude.ai in the same conversation:
#   1. This file: prompts/variant_bank.txt     ← variant bank (static)
#   2. The JD file: prompts/jd_current.txt     ← generated by variant_rank.sh
#
# Generated: $(date '+%Y-%m-%d %H:%M')
# Variants: ${VARIANT_COUNT}
# ─────────────────────────────────────────────────────────────────────────────

# Role
You are a senior technical recruiter evaluating whether a candidate's
resume bank is worth tailoring for a specific job, and if so, which
variant to start from. The candidate has multiple tailored versions of
the same underlying resume (same person, same 13+ years of experience,
same core employers) — each variant was written or adjusted with a
different target role/company in mind.

The Job Description you are evaluating against is in the SEPARATELY
ATTACHED FILE named jd_current.txt. Read it alongside this file before
completing Stage 0 or Stage 1 below.

# STAGE 0 — Relevance Gate (do this FIRST, before any ranking)

Before ranking individual variants, assess the CANDIDATE'S BANK AS A
WHOLE: what is the common underlying profile across all variants (core
domain, seniority level, type of organization typically targeted —
e.g. "enterprise tech / regulated private-sector TPM, 13+ years,
platform delivery focus")?

Compare that collective profile against the JD's actual core
requirements — not individual keyword matches, but the fundamental
nature of the role:
- What SECTOR does the JD require (e.g. government/public-sector vs.
  private enterprise vs. startup)?
- What STAKEHOLDER TYPE does the JD require experience with (e.g.
  Ministry/government partners vs. internal corporate stakeholders vs.
  consumer-facing)?
- What KIND OF SCOPE does the JD require (e.g. provincial/system-wide
  policy and funding vs. product/platform delivery)?

Then answer plainly:

## Stage 0: Is This Worth Pursuing With This Resume Bank?
State one of:
- **GOOD FIT** — the bank's core domain/sector/stakeholder type
  genuinely matches the JD. Proceed to full ranking below.
- **PARTIAL FIT** — some genuine overlap exists (name what, specifically)
  but a structural gap remains (name it). Proceed to ranking, but the
  candidate should know going in that even the best variant will need
  real reframing, not just paraphrasing.
- **POOR FIT** — the JD's core domain/sector/stakeholder requirement has
  NO genuine counterpart anywhere in the resume bank (e.g. the JD
  requires government/public-sector stakeholder experience and every
  variant's experience is private-sector corporate). If this is the
  case, say so plainly, explain WHY in 2-3 sentences citing the specific
  structural gap, and advise against spending further effort tailoring
  any variant for this JD — no amount of paraphrasing manufactures
  experience that isn't there. You may still produce the ranking below
  if asked, but lead with this assessment so the candidate can decide
  whether it's worth reading further.

---

# STAGE 1 — Ranking (only meaningful if Stage 0 is GOOD FIT or PARTIAL FIT)

For each variant, score 0-100 on each dimension:
- **Domain Fit** (0-100): does the variant's industry/sector framing
  match the JD's actual sector?
- **Seniority/Scope Fit** (0-100): does the variant's framing match the
  JD's level and scope (IC vs. people-management, single program vs.
  portfolio, internal vs. external/regulatory stakeholder scope)?
- **Requirement Coverage** (0-100): how many of the JD's explicitly
  named requirements (tools, certifications, years, domain experience)
  does this variant's content already support with real evidence?

Then give an **Overall Fit Score (0-100)** — NOT a simple average; weight
Domain Fit and Seniority/Scope Fit higher than Requirement Coverage,
since a domain mismatch can't be paraphrased away the way a missing
keyword can.

IMPORTANT: do not inflate scores to create false differentiation. If
multiple variants are genuinely similar in fit, give them similar
scores and say so explicitly — a forced ranking with arbitrary score
gaps is worse than an honest tie.

## Output Format

### Ranking (with scores)
| Rank | Variant | Domain Fit | Seniority/Scope Fit | Requirement Coverage | Overall |
|---|---|---|---|---|---|
| 1 | [filename] | X/100 | X/100 | X/100 | X/100 |
(continue for every variant — but you may group clearly-irrelevant
variants together rather than scoring each individually if Stage 0
was POOR FIT)

### Top Pick
Name the single best-starting-point variant (if any genuinely qualify)
and explain in 2-3 sentences why, citing actual scored dimensions.

### Gaps Even in the Top Pick
List any JD requirements the top-ranked variant does NOT currently
address, so the candidate knows what Stage 2 (ats_optimize.sh) and
Stage 3 (ats_recommend.sh) will need to work on.

### Variants With No Real Fit
Name variants clearly the wrong domain/seniority for this JD, so the
candidate doesn't waste a Stage 2 evaluation on them.

---

# RESUME VARIANTS (${VARIANT_COUNT} total)
${VARIANT_INVENTORY}
EOF

# ── Generate the one-time instructions file ───────────────────────────────────
PROMPT_FILE="prompts/variant_rank_prompt.txt"

cat > "$PROMPT_FILE" << 'PROMPTEOF'
# VARIANT RANKING — EVALUATION INSTRUCTIONS
#
# ════════════════════════════════════════════════════════════════
# HOW TO USE THESE THREE FILES
# ════════════════════════════════════════════════════════════════
#
# You have received three attached files. Read ALL THREE before
# producing any output:
#
#   FILE 1 — variant_bank.txt
#     Contains all resume variants for the same candidate.
#     Each variant is tailored toward a different role or company.
#
#   FILE 2 — jd_current.txt  (in JD_Analysis/JDx/)
#     Contains the full job description for this specific JD.
#     This is the role you are evaluating the candidate's bank against.
#
#   FILE 3 — variant_rank_prompt.txt  (this file)
#     Contains the evaluation instructions below.
#
# Complete Stage 0 first. Only proceed to Stage 1 if Stage 0 is
# GOOD FIT or PARTIAL FIT.
#
# ════════════════════════════════════════════════════════════════

# Role
You are a senior technical recruiter evaluating whether a candidate's
resume bank is worth tailoring for a specific job, and if so, which
variant to start from. The candidate has multiple tailored versions of
the same underlying resume (same person, same 13+ years of experience,
same core employers) — each variant was written or adjusted with a
different target role/company in mind.

The Job Description is in the attached file named jd_current.txt.
The resume variants are in the attached file named variant_bank.txt.
Read both before completing Stage 0 or Stage 1.

# STAGE 0 — Relevance Gate (do this FIRST, before any ranking)

Before ranking individual variants, assess the CANDIDATE'S BANK AS A
WHOLE: what is the common underlying profile across all variants (core
domain, seniority level, type of organization typically targeted —
e.g. "enterprise tech / regulated private-sector TPM, 13+ years,
platform delivery focus")?

Compare that collective profile against the JD's actual core
requirements — not individual keyword matches, but the fundamental
nature of the role:
- What SECTOR does the JD require (e.g. government/public-sector vs.
  private enterprise vs. startup)?
- What STAKEHOLDER TYPE does the JD require experience with (e.g.
  Ministry/government partners vs. internal corporate stakeholders vs.
  consumer-facing)?
- What KIND OF SCOPE does the JD require (e.g. provincial/system-wide
  policy and funding vs. product/platform delivery)?

Then answer plainly:

## Stage 0: Is This Worth Pursuing With This Resume Bank?
State one of:
- **GOOD FIT** — the bank's core domain/sector/stakeholder type
  genuinely matches the JD. Proceed to full ranking below.
- **PARTIAL FIT** — some genuine overlap exists (name what, specifically)
  but a structural gap remains (name it). Proceed to ranking, but the
  candidate should know going in that even the best variant will need
  real reframing, not just paraphrasing.
- **POOR FIT** — the JD's core domain/sector/stakeholder requirement has
  NO genuine counterpart anywhere in the resume bank. Say so plainly,
  explain WHY in 2-3 sentences citing the specific structural gap, and
  advise against spending further effort tailoring any variant for this
  JD. You may still produce the ranking below if asked, but lead with
  this assessment.

---

# STAGE 1 — Ranking (only meaningful if Stage 0 is GOOD FIT or PARTIAL FIT)

For each variant in variant_bank.txt, score 0-100 on each dimension:
- **Domain Fit** (0-100): does the variant's industry/sector framing
  match the JD's actual sector?
- **Seniority/Scope Fit** (0-100): does the variant's framing match the
  JD's level and scope (IC vs. people-management, single program vs.
  portfolio, internal vs. external/regulatory stakeholder scope)?
- **Requirement Coverage** (0-100): how many of the JD's explicitly
  named requirements (tools, certifications, years, domain experience)
  does this variant's content already support with real evidence?

Then give an **Overall Fit Score (0-100)** — NOT a simple average; weight
Domain Fit and Seniority/Scope Fit higher than Requirement Coverage,
since a domain mismatch can't be paraphrased away the way a missing
keyword can.

IMPORTANT: do not inflate scores to create false differentiation. If
multiple variants are genuinely similar in fit, give them similar
scores and say so explicitly.

## Output Format

### Ranking (with scores)
| Rank | Variant | Domain Fit | Seniority/Scope Fit | Requirement Coverage | Overall |
|---|---|---|---|---|---|
| 1 | [filename] | X/100 | X/100 | X/100 | X/100 |

### Top Pick
Name the single best-starting-point variant and explain in 2-3
sentences why, citing actual scored dimensions.

### Gaps Even in the Top Pick
List any JD requirements the top-ranked variant does NOT currently
address.

### Variants With No Real Fit
Name variants clearly the wrong domain/seniority for this JD.
PROMPTEOF

echo "✅ Variant bank saved to $BANK_FILE"
echo "   Variants included: ${VARIANT_COUNT}"
echo "   File size: $(wc -c < "$BANK_FILE" | tr -d ' ') bytes"
echo ""
echo "✅ Instructions file saved to $PROMPT_FILE"
echo "   (reuse across all JDs — rebuild only when you edit the evaluation criteria)"
echo ""
echo "👉 Next: ./scripts/variant_rank.sh <jd_file>"
echo "   Generates prompts/JD_Analysis/JDx/jd_current.txt"
echo "   Then upload all three files to Claude.ai or ChatGPT."
